name: CI
on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: password
      AWS_ENDPOINT_URL: http://localhost:9000
      AWS_REGION: us-east-1
    services:
      rest:
        image: apache/iceberg-rest-fixture
        env:
          AWS_ACCESS_KEY_ID: root
          AWS_SECRET_ACCESS_KEY: password
          AWS_ENDPOINT_URL: http://minio:9000
          AWS_REGION: us-east-1
          CATALOG_S3_ENDPOINT: http://minio:9000
          CATALOG_WAREHOUSE: s3://warehouse
          CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
        volumes:
          - ${{ github.workspace }}/assets/rest:/tmp
        ports:
          - "8181:8181"
      minio:
        image: minio/minio:latest
        ports:
          - "9000:9000" # MinIO API port
          - "9001:9001" # MinIO Console port
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: password
          MINIO_DOMAIN: minio
        volumes:
          - ${{ github.workspace }}/assets/minio/data:/data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build and test
        run: make all LIB_NAME="libiceberg_rust_ffi.so"